### ISSUE TITLE
Consider increasing accuracy of pull request merging trigger

### ISSUE THREAD

**Issue by JamesMGreene** [skills/introduction-to-github#2]
We currently use pushes to the `main` branch as the trigger for checking that a pull request was merged:

https://github.com/githublearn/introduction-to-github/blob/60017ba97de7a27dcd93d192d238c00cc280dfb0/.github/workflows/4-merge-your-pull-request.yml#L7-L13

While it's true that merging a PR into the `main` branch will trigger in just such an event, it is also true that many _other_ activities (like editing in the UI, other pushes, merging _other_ PRs, etc.) could also result in that trigger. 😅 

As such, we may want to consider increasing the accuracy of this event trigger if any folks start reporting such issues. 🤷🏻‍♂️ 

e.g. suggested:

```yaml
on:
  # Note that supporting `workflow_dispatch` will require some extra logic checks if
  # if we switch to using `pull_request` instead of `push`!
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - closed
```

_Plus_ updating the job-level `if` from:

https://github.com/githublearn/introduction-to-github/blob/60017ba97de7a27dcd93d192d238c00cc280dfb0/.github/workflows/4-merge-your-pull-request.yml#L24-L29

to:

```yaml
    if: ${{ github.repository_owner != 'githublearn' && github.event.pull_request.merged == true }}
```

We could _also_ get specific about the name of the PR head branch, if that makes sense:

```yaml
    if: >-
      ${{
        github.repository_owner != 'githublearn' &&
        github.event.pull_request.merged == true &&
        github.head_ref == 'pr_branch_name'
      }}
```

:warning: To still support `workflow_dispatch`, we would need to tweak the `if` condition further as well, e.g. something like:

```yaml
    if: >-
      ${{
        github.repository_owner != 'githublearn' &&
        (
          github.event_name == 'workflow_dispatch' ||
          (
            github.event.pull_request.merged == true &&
            github.head_ref == 'pr_branch_name'
          )
        )
      }}
```
